# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: true
jdk: oraclejdk9
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - art1828@mail.ru
    on_success: always # default: change
    on_failure: always # default: always
addons:
  apt:
    sources:
      - mysql-5.7
    packages:
      - mysql-server
      - mysql-client
before_install:
  - sudo mysql_upgrade --force
  - sudo mysql -e "use mysql; CREATE USER 'otus'@'localhost' IDENTIFIED BY '12345';"
  - sudo mysql -e "CREATE DATABASE IF NOT EXISTS otus; GRANT ALL ON otus.* TO 'otus'@'localhost'; FLUSH PRIVILEGES;"
  - sudo mysql -e "use otus; CREATE TABLE myORM(id bigint(20) NOT NULL, name varchar(255), age int(3));"
